Version: 0.1.1
auth:
  default:
    domain: workgroup.com
    encryptedPassword: Cl+sBAAAA7Eqo9p
    password: ''
    username: foo
  dpapiScope: machine
backupLocation: ifs\cluster\mfg_swd
backupServerIps:
- 102.121.143.87
- backupServerHost
computer2Backup:
- this Computer:
    Backups:
    - C:\
    - C:\foo
    Connection:
      Domain: workgroup
      EncryptedPassword: Cl+sBAAAA7Eqo9pxWxk
      Host: 192.168.1.91
      Password: ''
      Username: foo
    Exclude:
    - regex ^C:\\foo\\[0-9]{8}\\.*
- remote_computer_1:
    Backups:
    - \\192.168.1.31\C$\foo
    - \\192.168.1.31\C$\RTS fooBar
    - \\192.168.1.31\D$
    Connection:
      Domain: workgroup
      Host: 192.168.1.31
      Password: ''
      Username: foo
    Exclude:
    - \\192.168.1.31\C$\foo\*.log
- remote_computer_2:
    Backups:
    - \\192.168.1.162\foo
    Connection:
      Domain: workgroup
      EncryptedPassword: ''
      Host: 192.168.1.162
      Password: ''
      Username: foo
- remote_computer_3:
    Backups:
    - \\192.168.1.201\foo
    Connection:
      Domain: workgroup
      EncryptedPassword: ''
      Host: 192.168.1.201
      Password: ''
      Username: foo
    Exclude: []
logLvl: 4
retentionCount: 14
schedule:
  cron: '*/5 0/2 * * *'
tempRoot: C:\Temp\Backups
